### ISSUE TITLE
Outdated versions

### ISSUE THREAD

**Issue by magneticflux-** [Choumiko/TheFatController#10]
The latest version on factoriomods.com is 0.2.4; the latest version here is 0.4.14

**Comment by Choumiko** [comment]
I'm aware of that. The FatController on factoriomods isn't editable by me. I pm'ed the creator of the site to transfer ownership to me but he also seems to be MIA

**Comment by magneticflux-** [comment]
This is how to update the mod, courtesy of the creator: https://github.com/Zequez/FactorioMods/issues/7

Useful bits:

> For now, until that's done, the recommended way would be to just submit a mod with the same name, it's not forbidden by validation, and both mods will show up if you search them on the API by mods?names=<mod_name>.

**Comment by Choumiko** [comment]
Ha, i would have never tried that.. thanks, FatController and Railtanker are now updated
