### ISSUE TITLE
MP DeSync issue when remote viewing + new connection

### ISSUE THREAD

**Issue by Nexela** [Choumiko/TheFatController#14]
This is not thoroughly tested as there are a million other mods installed also. using latest Factorio and Fat Controller (as well as all the other train mods you have :)

DeSync issue only happens If you are remotely viewing a train and someone connects to you. All other times the remote viewing works fine.

**Comment by Choumiko** [comment]
Wasn't able to reproduce it.
Tried on one PC with
- Headless server, 2 clients. 1 was remote controlling a train, the other joined/left. Joined as a new Player
- Same as above, only that client 1 was also the server

Can you post a modlist and/or save?

**Comment by Nexela** [comment]
Well I can't reproduce it now either. If I get it to happen again I will throw up the save and modlist. As a side note it is possible it is related to YARM.  Shortly after this issue we were getting chain desyncs when my sister was connecting. Removing YARM and Research Queue fixed those. YARM had to go as I was dying to biters while viewing sites :) and RQ was giving massive performance hits when opened. So no loss on removing these 2 mods.

**Comment by Choumiko** [comment]
Most likely outdated/fixed
