### ISSUE TITLE
Error/Desync when clicking UI (Trains +/-)

### ISSUE THREAD

**Issue by Sakata-MC** [Choumiko/TheFatController#16]
Also seems to do this when starting/stopping FARL

Get a message right before the desync:
do local var={element={__self="userdata: 0x4######"},name=1,player_index=1,tick=######};return var;end

If any further info is needed, will be happy to provide it.

**Comment by Choumiko** [comment]
I assume you are using AutoTrash too?
Should be fixed then in the latest release: https://github.com/Choumiko/AutoTrash/releases/tag/v0.1.1
