### ISSUE TITLE
Feature Request - GUI main Replace text button with icon button

### ISSUE THREAD

**Issue by Nexela** [Choumiko/TheFatController#17]
Just a friendly reminder for when you feel like getting around to it. I wouldn't even be opposed to it being as simple as the train recipe icon.  This is the last mod that I use that needs gui updating.  Well except for shuttle train but I don't use it enough so I might get rid of it.

Thanks again!

**Comment by Choumiko** [comment]
Done: https://mods.factorio.com/mods/Choumiko/TheFatController
