### ISSUE TITLE
incompatible with 0.16.22

### ISSUE THREAD

**Issue by Gforce4u** [Choumiko/TheFatController#27]
error with 0.16.22 :
error while loading entity prototype "fatcontroller" (player): Keyënter_vehicle_distance" not found in property tree at ROOT.player.fatcontroller

**Comment by sapid** [comment]
More info: in 0.16.22 [release notes](https://forums.factorio.com/viewtopic.php?f=3&t=57402) enter_vehicle_distance was added to [`LuaEntityPrototype`](http://lua-api.factorio.com/latest/LuaEntityPrototype.html#LuaEntityPrototype.enter_vehicle_distance).

**Comment by Nexela** [comment]
Fixed for the next release of factorio.  A default will be applied

**Comment by sapid** [comment]
It looks like a lot of the defaults are overridden here, so it's probably best to overwrite the default here as well, regardless of whether or not the variable's absence is acceptable.

The fix is really minor. Merging the above pull request should close this issue.
