### ISSUE TITLE
Stuck in "ghost mode" ?

### ISSUE THREAD

**Issue by Panderine** [Choumiko/TheFatController#34]
I got killed while following a train in TFC. Now I'm stuck in ghots mode, I can interact with things but I move at super speed, and don't see the player. How can i get out of this? :(

**Comment by Choumiko** [comment]
Try using /fat_fix_character in the console. This should return you to your original character.

**Comment by Choumiko** [comment]
I just realised that the above command probably won't help you..
Instead try this:
`/c game.player.character = game.player.surface.create_entity{name="character", position = game.player.position}`

I'll have an update up soon that fixes the cause.

**Comment by Panderine** [comment]
Thanks I went back to an autosave. Will keep this commands as reference for
next time. This was the first time I got bugged while being killed.
