### ISSUE TITLE
Line 295, found and fixed and error locally

### ISSUE THREAD

**Issue by tpdatta** [Choumiko/TheFatController#5]
![fixed issue](https://cloud.githubusercontent.com/assets/9919583/14696101/4891b3e2-0746-11e6-87b9-3785bd9e5ad2.PNG)

I changed this line of code after loading a save and it saying that guisettings were nil. Thought you might want to add it to the repo.

Line 295
       `global.guisettings ~= nil and`
was added before
       `global.guisettings[i]`

I did it as a quick fix, not sure of the reprecoussions yet. but thought you might like to take a look

**Comment by Choumiko** [comment]
what version/file is that? In the latest release i can't find it.

**Comment by tpdatta** [comment]
Sorry, forgot to mention that.

 It is in `control.lua`, `version 0.3.1`

**Comment by Choumiko** [comment]
0.3.1 is way outdated.
Unless you're able to reproduce it with https://github.com/Choumiko/TheFatController/releases/tag/v0.4.11 i'll consider it as fixed.
