### ISSUE TITLE
Character can only be connected to one player at Time

### ISSUE THREAD

**Issue by Dominik-O22** [Choumiko/TheFatController#6]
After shortly remotely controlling a train i now get this chat spam 
`__TheFatController__ /controll.lua:823: Character can only be connected to one player at a time`

running version 0.12.29 of factorio and version 0.3.15 of Fat controller

**Comment by Choumiko** [comment]
0.3.15 is seriously outdated, use: https://github.com/Choumiko/TheFatController/releases/tag/v0.4.11

If the only problem is the spam, simply updating should be fine. If you are stuck in the remote mode you have to locate your character, move the mouse over it and use:
/c game.local_player.character = game.local_player.selected
in the console. (paste the code in the console first, then hover over your character and hit enter)

**Comment by Dominik-O22** [comment]
okay updated the mod now, but now when i try to control a train get these error messages
![image](https://cloud.githubusercontent.com/assets/12860183/14761268/706aba00-095b-11e6-9a75-d7c6489fe5cd.png)

**Comment by Choumiko** [comment]
This looks like a leftover from 0.3.15, try the following:
- Make a backup of the save
- Disable FatController
- Load the save
- Save it
- Enable FatController
- Load the save

I should add a command to do this (and fix all the upgrading issues)

**Comment by Dominik-O22** [comment]
yay it works now thank you
